language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.dev.txt
    - python setup.py build_ext --inplace
script:
    - py.test tests/
    - flake8
