language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.dev.txt
    - pip install .
script:
    - make test
