language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.dev.txt
    - python setup.py bdist_wheel
    - pip install dist/*.whl
script:
    - py.test tests/
    - flake8
