name: build

on: [push]

jobs:
  build_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
   
      - name: Setup pip
        run: python -m pip install --upgrade pip
    
      - name: Build source distribution
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.tar.gz

  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
   
      - name: Setup pip
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements-dev.txt
    
      - name: Build wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl

  publish:
    runs-on: ubuntu-latest
    needs: [build_source, build_wheels]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          verbose: true
